### ISSUE TITLE
Documentation? 

### ISSUE THREAD

**Issue by TammyLaforest** [jamesqquick/Web-Boilerplate-VSCE#1]
Do you have instructions for this extension?

**Comment by jamesqquick** [comment]
Thanks for checking it out! What kind of instructions would you be looking for? How to generate the files?

**Comment by TammyLaforest** [comment]
Yes. Any sort of "how to" would be great. Thanks.

**Comment by jamesqquick** [comment]
Added a quick set of instructions with screenshot. Thanks for the feedback!
